// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/usecases/ai_generation_usecases_complete_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i5;
import 'package:voice_autobiography_flutter/domain/entities/autobiography.dart'
    as _i7;
import 'package:voice_autobiography_flutter/domain/entities/chapter.dart'
    as _i9;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/repositories/ai_generation_repository.dart'
    as _i3;
import 'package:voice_autobiography_flutter/domain/services/autobiography_structure_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiGenerationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiGenerationRepository extends _i1.Mock
    implements _i3.AiGenerationRepository {
  MockAiGenerationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateAutobiography({
    required List<_i6.VoiceRecord>? voiceRecords,
    _i7.AutobiographyStyle? style,
    int? wordCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAutobiography,
          [],
          {
            #voiceRecords: voiceRecords,
            #style: style,
            #wordCount: wordCount,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateAutobiography,
            [],
            {
              #voiceRecords: voiceRecords,
              #style: style,
              #wordCount: wordCount,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> optimizeAutobiography({
    required String? content,
    _i7.OptimizationType? optimizationType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeAutobiography,
          [],
          {
            #content: content,
            #optimizationType: optimizationType,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #optimizeAutobiography,
            [],
            {
              #content: content,
              #optimizationType: optimizationType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateTitle(
          {required String? content}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTitle,
          [],
          {#content: content},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateTitle,
            [],
            {#content: content},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateSummary(
          {required String? content}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSummary,
          [],
          {#content: content},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateSummary,
            [],
            {#content: content},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i8.StructureUpdatePlan>> analyzeStructure({
    required String? newContent,
    required List<_i9.Chapter>? currentChapters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeStructure,
          [],
          {
            #newContent: newContent,
            #currentChapters: currentChapters,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.StructureUpdatePlan>>.value(
                _FakeEither_0<_i5.Failure, _i8.StructureUpdatePlan>(
          this,
          Invocation.method(
            #analyzeStructure,
            [],
            {
              #newContent: newContent,
              #currentChapters: currentChapters,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.StructureUpdatePlan>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateChapterContent({
    String? originalContent,
    required String? newVoiceContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateChapterContent,
          [],
          {
            #originalContent: originalContent,
            #newVoiceContent: newVoiceContent,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateChapterContent,
            [],
            {
              #originalContent: originalContent,
              #newVoiceContent: newVoiceContent,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
