// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/usecases/autobiography_version_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i5;
import 'package:voice_autobiography_flutter/domain/entities/autobiography_version.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/repositories/autobiography_version_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AutobiographyVersionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutobiographyVersionRepository extends _i1.Mock
    implements _i3.AutobiographyVersionRepository {
  MockAutobiographyVersionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>> saveVersion({
    required String? autobiographyId,
    required String? versionName,
    required String? content,
    required List<Map<String, dynamic>>? chapters,
    required int? wordCount,
    String? summary,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVersion,
          [],
          {
            #autobiographyId: autobiographyId,
            #versionName: versionName,
            #content: content,
            #chapters: chapters,
            #wordCount: wordCount,
            #summary: summary,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>>.value(
                _FakeEither_0<_i5.Failure, _i6.AutobiographyVersion>(
          this,
          Invocation.method(
            #saveVersion,
            [],
            {
              #autobiographyId: autobiographyId,
              #versionName: versionName,
              #content: content,
              #chapters: chapters,
              #wordCount: wordCount,
              #summary: summary,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.AutobiographyVersion>>> getVersions(
          {required String? autobiographyId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersions,
          [],
          {#autobiographyId: autobiographyId},
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i6.AutobiographyVersion>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.AutobiographyVersion>>(
          this,
          Invocation.method(
            #getVersions,
            [],
            {#autobiographyId: autobiographyId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AutobiographyVersion>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>> getVersion(
          {required String? versionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersion,
          [],
          {#versionId: versionId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>>.value(
                _FakeEither_0<_i5.Failure, _i6.AutobiographyVersion>(
          this,
          Invocation.method(
            #getVersion,
            [],
            {#versionId: versionId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AutobiographyVersion>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteVersion(
          {required String? versionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVersion,
          [],
          {#versionId: versionId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteVersion,
            [],
            {#versionId: versionId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getVersionCount(
          {required String? autobiographyId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVersionCount,
          [],
          {#autobiographyId: autobiographyId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getVersionCount,
            [],
            {#autobiographyId: autobiographyId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteOldestVersion(
          {required String? autobiographyId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldestVersion,
          [],
          {#autobiographyId: autobiographyId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteOldestVersion,
            [],
            {#autobiographyId: autobiographyId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
