// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/bloc/ai_generation_bloc_complete_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i5;
import 'package:voice_autobiography_flutter/data/services/ai_generation_persistence_service.dart'
    as _i10;
import 'package:voice_autobiography_flutter/data/services/background_ai_service.dart'
    as _i9;
import 'package:voice_autobiography_flutter/domain/entities/autobiography.dart'
    as _i7;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/repositories/autobiography_repository.dart'
    as _i8;
import 'package:voice_autobiography_flutter/domain/usecases/ai_generation_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiGenerationUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiGenerationUseCases extends _i1.Mock
    implements _i3.AiGenerationUseCases {
  MockAiGenerationUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateAutobiography({
    required List<_i6.VoiceRecord>? voiceRecords,
    _i7.AutobiographyStyle? style = _i7.AutobiographyStyle.narrative,
    int? wordCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAutobiography,
          [],
          {
            #voiceRecords: voiceRecords,
            #style: style,
            #wordCount: wordCount,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateAutobiography,
            [],
            {
              #voiceRecords: voiceRecords,
              #style: style,
              #wordCount: wordCount,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> optimizeAutobiography({
    required String? content,
    _i7.OptimizationType? optimizationType = _i7.OptimizationType.clarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeAutobiography,
          [],
          {
            #content: content,
            #optimizationType: optimizationType,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #optimizeAutobiography,
            [],
            {
              #content: content,
              #optimizationType: optimizationType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateTitle(
          {required String? content}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateTitle,
          [],
          {#content: content},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateTitle,
            [],
            {#content: content},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> generateSummary(
          {required String? content}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSummary,
          [],
          {#content: content},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #generateSummary,
            [],
            {#content: content},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.AutobiographyGenerationResult>>
      generateCompleteAutobiography({
    required List<_i6.VoiceRecord>? voiceRecords,
    _i7.AutobiographyStyle? style = _i7.AutobiographyStyle.narrative,
    int? wordCount,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateCompleteAutobiography,
              [],
              {
                #voiceRecords: voiceRecords,
                #style: style,
                #wordCount: wordCount,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i3.AutobiographyGenerationResult>>.value(
                _FakeEither_0<_i5.Failure, _i3.AutobiographyGenerationResult>(
              this,
              Invocation.method(
                #generateCompleteAutobiography,
                [],
                {
                  #voiceRecords: voiceRecords,
                  #style: style,
                  #wordCount: wordCount,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i3.AutobiographyGenerationResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.IncrementalUpdateResult>>
      incrementalUpdateAutobiography({
    required String? newVoiceContent,
    _i7.Autobiography? currentAutobiography,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #incrementalUpdateAutobiography,
              [],
              {
                #newVoiceContent: newVoiceContent,
                #currentAutobiography: currentAutobiography,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i3.IncrementalUpdateResult>>.value(
                _FakeEither_0<_i5.Failure, _i3.IncrementalUpdateResult>(
              this,
              Invocation.method(
                #incrementalUpdateAutobiography,
                [],
                {
                  #newVoiceContent: newVoiceContent,
                  #currentAutobiography: currentAutobiography,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i3.IncrementalUpdateResult>>);
}

/// A class which mocks [AutobiographyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutobiographyRepository extends _i1.Mock
    implements _i8.AutobiographyRepository {
  MockAutobiographyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getAllAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getAllAutobiographies,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getAllAutobiographies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>> getAutobiographyById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutobiographyById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>>.value(
                _FakeEither_0<_i5.Failure, _i7.Autobiography>(
          this,
          Invocation.method(
            #getAutobiographyById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> insertAutobiography(
          _i7.Autobiography? autobiography) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAutobiography,
          [autobiography],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #insertAutobiography,
            [autobiography],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateAutobiography(
          _i7.Autobiography? autobiography) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutobiography,
          [autobiography],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateAutobiography,
            [autobiography],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAutobiography(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutobiography,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteAutobiography,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      searchAutobiographies(String? query) => (super.noSuchMethod(
            Invocation.method(
              #searchAutobiographies,
              [query],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #searchAutobiographies,
                [query],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getAutobiographiesByStatus(_i7.AutobiographyStatus? status) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAutobiographiesByStatus,
              [status],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getAutobiographiesByStatus,
                [status],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getAutobiographiesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAutobiographiesByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getAutobiographiesByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography?>>
      getLatestAutobiography() => (super.noSuchMethod(
            Invocation.method(
              #getLatestAutobiography,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography?>>.value(
                    _FakeEither_0<_i5.Failure, _i7.Autobiography?>(
              this,
              Invocation.method(
                #getLatestAutobiography,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getDraftAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getDraftAutobiographies,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getDraftAutobiographies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getPublishedAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getPublishedAutobiographies,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getPublishedAutobiographies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>
      getArchivedAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getArchivedAutobiographies,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Autobiography>>(
              this,
              Invocation.method(
                #getArchivedAutobiographies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Autobiography>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateAutobiographyStatus(
    String? id,
    _i7.AutobiographyStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutobiographyStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateAutobiographyStatus,
            [
              id,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAutobiographies(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutobiographies,
          [ids],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteAutobiographies,
            [ids],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getAutobiographyStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getAutobiographyStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAutobiographyStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> exportAutobiography(
    String? id,
    String? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAutobiography,
          [
            id,
            format,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #exportAutobiography,
            [
              id,
              format,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>> importAutobiography(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAutobiography,
          [filePath],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>>.value(
                _FakeEither_0<_i5.Failure, _i7.Autobiography>(
          this,
          Invocation.method(
            #importAutobiography,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Autobiography>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> backupAutobiographies() =>
      (super.noSuchMethod(
        Invocation.method(
          #backupAutobiographies,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #backupAutobiographies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> restoreAutobiographies(
          String? backupPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAutobiographies,
          [backupPath],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #restoreAutobiographies,
            [backupPath],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [BackgroundAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundAiService extends _i1.Mock
    implements _i9.BackgroundAiService {
  MockBackgroundAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> startBackgroundTask({String? taskDescription}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startBackgroundTask,
          [],
          {#taskDescription: taskDescription},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> updateNotification({
    required String? title,
    required String? text,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotification,
          [],
          {
            #title: title,
            #text: text,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stopBackgroundTask() => (super.noSuchMethod(
        Invocation.method(
          #stopBackgroundTask,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isServiceRunning() => (super.noSuchMethod(
        Invocation.method(
          #isServiceRunning,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AiGenerationPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiGenerationPersistenceService extends _i1.Mock
    implements _i10.AiGenerationPersistenceService {
  MockAiGenerationPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveGenerationState({
    required String? generationType,
    required List<String>? voiceRecordIds,
    String? currentAutobiographyId,
    String? generatedContent,
    String? generatedTitle,
    String? generatedSummary,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGenerationState,
          [],
          {
            #generationType: generationType,
            #voiceRecordIds: voiceRecordIds,
            #currentAutobiographyId: currentAutobiographyId,
            #generatedContent: generatedContent,
            #generatedTitle: generatedTitle,
            #generatedSummary: generatedSummary,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateGenerationProgress({
    String? generatedContent,
    String? generatedTitle,
    String? generatedSummary,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGenerationProgress,
          [],
          {
            #generatedContent: generatedContent,
            #generatedTitle: generatedTitle,
            #generatedSummary: generatedSummary,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasUnfinishedTask() => (super.noSuchMethod(
        Invocation.method(
          #hasUnfinishedTask,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> clearGenerationState() => (super.noSuchMethod(
        Invocation.method(
          #clearGenerationState,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool isTaskTimeout() => (super.noSuchMethod(
        Invocation.method(
          #isTaskTimeout,
          [],
        ),
        returnValue: false,
      ) as bool);
}
