// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/bloc/integrated_recording_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/data/services/enhanced_audio_recording_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EnhancedAudioRecordingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnhancedAudioRecordingService extends _i1.Mock
    implements _i2.EnhancedAudioRecordingService {
  MockEnhancedAudioRecordingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRecording => (super.noSuchMethod(
        Invocation.getter(#isRecording),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isFileUpload => (super.noSuchMethod(
        Invocation.getter(#isFileUpload),
        returnValue: false,
      ) as bool);

  @override
  Duration get recordingDuration => (super.noSuchMethod(
        Invocation.getter(#recordingDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#recordingDuration),
        ),
      ) as Duration);

  @override
  set onRecognitionResult(
          dynamic Function(
            String,
            double,
          )? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #onRecognitionResult,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onError(dynamic Function(String)? value) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onStarted(dynamic Function()? value) => super.noSuchMethod(
        Invocation.setter(
          #onStarted,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onCompleted(dynamic Function()? value) => super.noSuchMethod(
        Invocation.setter(
          #onCompleted,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> startRecordingWithRecognition({
    required dynamic Function(
      String,
      double,
    )? onResult,
    dynamic Function(String)? onError,
    dynamic Function()? onStarted,
    dynamic Function()? onCompleted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecordingWithRecognition,
          [],
          {
            #onResult: onResult,
            #onError: onError,
            #onStarted: onStarted,
            #onCompleted: onCompleted,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> recognizeFile(
    String? filePath, {
    required dynamic Function(
      String,
      double,
    )? onResult,
    dynamic Function(String)? onError,
    dynamic Function()? onStarted,
    dynamic Function()? onCompleted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recognizeFile,
          [filePath],
          {
            #onResult: onResult,
            #onError: onError,
            #onStarted: onStarted,
            #onCompleted: onCompleted,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pauseRecording() => (super.noSuchMethod(
        Invocation.method(
          #pauseRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resumeRecording() => (super.noSuchMethod(
        Invocation.method(
          #resumeRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cancelRecording() => (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<double> getAudioAmplitudeStream() => (super.noSuchMethod(
        Invocation.method(
          #getAudioAmplitudeStream,
          [],
        ),
        returnValue: _i3.Stream<double>.empty(),
      ) as _i3.Stream<double>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
