// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/bloc/voice_record_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i6;
import 'package:voice_autobiography_flutter/data/services/auto_tagger_service.dart'
    as _i8;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i7;
import 'package:voice_autobiography_flutter/domain/repositories/voice_record_repository.dart'
    as _i4;
import 'package:voice_autobiography_flutter/domain/usecases/recording_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerateAutobiographyUseCase_1 extends _i1.SmartFake
    implements _i3.GenerateAutobiographyUseCase {
  _FakeGenerateAutobiographyUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecordRepository extends _i1.Mock
    implements _i4.VoiceRecordRepository {
  MockVoiceRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>
      getAllVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getAllVoiceRecords,
              [],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceRecord>>(
              this,
              Invocation.method(
                #getAllVoiceRecords,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>> getVoiceRecordById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRecordById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceRecord>(
          this,
          Invocation.method(
            #getVoiceRecordById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> insertVoiceRecord(
          _i7.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #insertVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> updateVoiceRecord(
          _i7.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #updateVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteVoiceRecord(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecord,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecord,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>> searchVoiceRecords(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVoiceRecords,
          [query],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceRecord>>(
          this,
          Invocation.method(
            #searchVoiceRecords,
            [query],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>
      getVoiceRecordsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getVoiceRecordsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceRecord>>(
              this,
              Invocation.method(
                #getVoiceRecordsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>
      getProcessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getProcessedVoiceRecords,
              [],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceRecord>>(
              this,
              Invocation.method(
                #getProcessedVoiceRecords,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>
      getUnprocessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getUnprocessedVoiceRecords,
              [],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceRecord>>(
              this,
              Invocation.method(
                #getUnprocessedVoiceRecords,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceRecord>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> markAsProcessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsProcessed,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #markAsProcessed,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> markAsUnprocessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnprocessed,
          [id],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #markAsUnprocessed,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> deleteVoiceRecords(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecords,
          [ids],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecords,
            [ids],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, Map<String, dynamic>>>
      getRecordingStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getRecordingStatistics,
              [],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i6.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getRecordingStatistics,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [RecordingUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingUseCases extends _i1.Mock implements _i3.RecordingUseCases {
  MockRecordingUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GenerateAutobiographyUseCase get generateAutobiographyUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#generateAutobiographyUseCase),
        returnValue: _FakeGenerateAutobiographyUseCase_1(
          this,
          Invocation.getter(#generateAutobiographyUseCase),
        ),
      ) as _i3.GenerateAutobiographyUseCase);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> startRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #startRecording,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>> stopRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceRecord>(
          this,
          Invocation.method(
            #stopRecording,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceRecord>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> pauseRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseRecording,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #pauseRecording,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> resumeRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #resumeRecording,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #resumeRecording,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> cancelRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #cancelRecording,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [AutoTaggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoTaggerService extends _i1.Mock implements _i8.AutoTaggerService {
  MockAutoTaggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<String>> generateTags(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateTags,
          [content],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
}
