// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/integration/core_features_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i8;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i10;
import 'package:dio/src/dio.dart' as _i7;
import 'package:dio/src/dio_mixin.dart' as _i3;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i12;
import 'package:voice_autobiography_flutter/domain/entities/autobiography.dart'
    as _i15;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i13;
import 'package:voice_autobiography_flutter/domain/repositories/autobiography_repository.dart'
    as _i14;
import 'package:voice_autobiography_flutter/domain/repositories/voice_record_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_1 extends _i1.SmartFake implements _i3.Interceptors {
  _FakeInterceptors_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake
    implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_6<L, R> extends _i1.SmartFake implements _i8.Either<L, R> {
  _FakeEither_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  _i3.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_1(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i3.Interceptors);

  @override
  _i4.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_2(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i4.HttpClientAdapter);

  @override
  _i5.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_3(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i5.Transformer);

  @override
  set options(_i2.BaseOptions? value) => super.noSuchMethod(
        Invocation.setter(
          #options,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? value) => super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i5.Transformer? value) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<dynamic>>);

  @override
  _i9.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<dynamic>>);

  @override
  _i9.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i3.Interceptors? interceptors,
    _i4.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_5(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i7.Dio);
}

/// A class which mocks [VoiceRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecordRepository extends _i1.Mock
    implements _i11.VoiceRecordRepository {
  MockVoiceRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>
      getAllVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getAllVoiceRecords,
              [],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>.value(
                _FakeEither_6<_i12.Failure, List<_i13.VoiceRecord>>(
              this,
              Invocation.method(
                #getAllVoiceRecords,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, _i13.VoiceRecord>> getVoiceRecordById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRecordById,
          [id],
        ),
        returnValue:
            _i9.Future<_i8.Either<_i12.Failure, _i13.VoiceRecord>>.value(
                _FakeEither_6<_i12.Failure, _i13.VoiceRecord>(
          this,
          Invocation.method(
            #getVoiceRecordById,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, _i13.VoiceRecord>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> insertVoiceRecord(
          _i13.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #insertVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> updateVoiceRecord(
          _i13.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #updateVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> deleteVoiceRecord(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecord,
          [id],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecord,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>
      searchVoiceRecords(String? query) => (super.noSuchMethod(
            Invocation.method(
              #searchVoiceRecords,
              [query],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>.value(
                _FakeEither_6<_i12.Failure, List<_i13.VoiceRecord>>(
              this,
              Invocation.method(
                #searchVoiceRecords,
                [query],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>
      getVoiceRecordsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getVoiceRecordsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>.value(
                _FakeEither_6<_i12.Failure, List<_i13.VoiceRecord>>(
              this,
              Invocation.method(
                #getVoiceRecordsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>
      getProcessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getProcessedVoiceRecords,
              [],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>.value(
                _FakeEither_6<_i12.Failure, List<_i13.VoiceRecord>>(
              this,
              Invocation.method(
                #getProcessedVoiceRecords,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>
      getUnprocessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getUnprocessedVoiceRecords,
              [],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>.value(
                _FakeEither_6<_i12.Failure, List<_i13.VoiceRecord>>(
              this,
              Invocation.method(
                #getUnprocessedVoiceRecords,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i13.VoiceRecord>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> markAsProcessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsProcessed,
          [id],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #markAsProcessed,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> markAsUnprocessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnprocessed,
          [id],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #markAsUnprocessed,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> deleteVoiceRecords(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecords,
          [ids],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecords,
            [ids],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>
      getRecordingStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getRecordingStatistics,
              [],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>.value(
                _FakeEither_6<_i12.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getRecordingStatistics,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [AutobiographyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutobiographyRepository extends _i1.Mock
    implements _i14.AutobiographyRepository {
  MockAutobiographyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getAllAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getAllAutobiographies,
              [],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getAllAutobiographies,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>> getAutobiographyById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutobiographyById,
          [id],
        ),
        returnValue:
            _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>>.value(
                _FakeEither_6<_i12.Failure, _i15.Autobiography>(
          this,
          Invocation.method(
            #getAutobiographyById,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> insertAutobiography(
          _i15.Autobiography? autobiography) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAutobiography,
          [autobiography],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #insertAutobiography,
            [autobiography],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> updateAutobiography(
          _i15.Autobiography? autobiography) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutobiography,
          [autobiography],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #updateAutobiography,
            [autobiography],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> deleteAutobiography(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutobiography,
          [id],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #deleteAutobiography,
            [id],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      searchAutobiographies(String? query) => (super.noSuchMethod(
            Invocation.method(
              #searchAutobiographies,
              [query],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #searchAutobiographies,
                [query],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getAutobiographiesByStatus(_i15.AutobiographyStatus? status) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAutobiographiesByStatus,
              [status],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getAutobiographiesByStatus,
                [status],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getAutobiographiesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAutobiographiesByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getAutobiographiesByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography?>>
      getLatestAutobiography() => (super.noSuchMethod(
            Invocation.method(
              #getLatestAutobiography,
              [],
            ),
            returnValue:
                _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography?>>.value(
                    _FakeEither_6<_i12.Failure, _i15.Autobiography?>(
              this,
              Invocation.method(
                #getLatestAutobiography,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography?>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getDraftAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getDraftAutobiographies,
              [],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getDraftAutobiographies,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getPublishedAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getPublishedAutobiographies,
              [],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getPublishedAutobiographies,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>
      getArchivedAutobiographies() => (super.noSuchMethod(
            Invocation.method(
              #getArchivedAutobiographies,
              [],
            ),
            returnValue: _i9.Future<
                    _i8.Either<_i12.Failure, List<_i15.Autobiography>>>.value(
                _FakeEither_6<_i12.Failure, List<_i15.Autobiography>>(
              this,
              Invocation.method(
                #getArchivedAutobiographies,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, List<_i15.Autobiography>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> updateAutobiographyStatus(
    String? id,
    _i15.AutobiographyStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutobiographyStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #updateAutobiographyStatus,
            [
              id,
              status,
            ],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> deleteAutobiographies(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutobiographies,
          [ids],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #deleteAutobiographies,
            [ids],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>
      getAutobiographyStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getAutobiographyStatistics,
              [],
            ),
            returnValue: _i9
                .Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>.value(
                _FakeEither_6<_i12.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAutobiographyStatistics,
                [],
              ),
            )),
          ) as _i9.Future<_i8.Either<_i12.Failure, Map<String, dynamic>>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, String>> exportAutobiography(
    String? id,
    String? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAutobiography,
          [
            id,
            format,
          ],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, String>>.value(
            _FakeEither_6<_i12.Failure, String>(
          this,
          Invocation.method(
            #exportAutobiography,
            [
              id,
              format,
            ],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, String>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>> importAutobiography(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #importAutobiography,
          [filePath],
        ),
        returnValue:
            _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>>.value(
                _FakeEither_6<_i12.Failure, _i15.Autobiography>(
          this,
          Invocation.method(
            #importAutobiography,
            [filePath],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, _i15.Autobiography>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, String>> backupAutobiographies() =>
      (super.noSuchMethod(
        Invocation.method(
          #backupAutobiographies,
          [],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, String>>.value(
            _FakeEither_6<_i12.Failure, String>(
          this,
          Invocation.method(
            #backupAutobiographies,
            [],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, String>>);

  @override
  _i9.Future<_i8.Either<_i12.Failure, void>> restoreAutobiographies(
          String? backupPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAutobiographies,
          [backupPath],
        ),
        returnValue: _i9.Future<_i8.Either<_i12.Failure, void>>.value(
            _FakeEither_6<_i12.Failure, void>(
          this,
          Invocation.method(
            #restoreAutobiographies,
            [backupPath],
          ),
        )),
      ) as _i9.Future<_i8.Either<_i12.Failure, void>>);
}
