// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/integration/interview_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i9;
import 'package:voice_autobiography_flutter/data/services/database_service.dart'
    as _i12;
import 'package:voice_autobiography_flutter/data/services/doubao_ai_service.dart'
    as _i5;
import 'package:voice_autobiography_flutter/data/services/interview_question_pool.dart'
    as _i11;
import 'package:voice_autobiography_flutter/domain/entities/autobiography.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i10;
import 'package:voice_autobiography_flutter/domain/repositories/voice_record_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DoubaoAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoubaoAiService extends _i1.Mock implements _i5.DoubaoAiService {
  MockDoubaoAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> analyzeAutobiographyStructure({
    required String? newContent,
    required List<Map<String, dynamic>>? currentChapters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeAutobiographyStructure,
          [],
          {
            #newContent: newContent,
            #currentChapters: currentChapters,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> generateAutobiography({
    required List<String>? voiceContents,
    _i6.AutobiographyStyle? style = _i6.AutobiographyStyle.narrative,
    int? wordCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAutobiography,
          [],
          {
            #voiceContents: voiceContents,
            #style: style,
            #wordCount: wordCount,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateAutobiography,
            [],
            {
              #voiceContents: voiceContents,
              #style: style,
              #wordCount: wordCount,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> optimizeAutobiography({
    required String? originalContent,
    _i6.OptimizationType? optimizationType = _i6.OptimizationType.clarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeAutobiography,
          [],
          {
            #originalContent: originalContent,
            #optimizationType: optimizationType,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #optimizeAutobiography,
            [],
            {
              #originalContent: originalContent,
              #optimizationType: optimizationType,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateChapterContent({
    String? originalContent,
    required String? newVoiceContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateChapterContent,
          [],
          {
            #originalContent: originalContent,
            #newVoiceContent: newVoiceContent,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateChapterContent,
            [],
            {
              #originalContent: originalContent,
              #newVoiceContent: newVoiceContent,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateTitle(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateTitle,
          [content],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateTitle,
            [content],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateSummary(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateSummary,
          [content],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateSummary,
            [content],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateInterviewQuestion({
    required String? userContentSummary,
    required List<String>? answeredQuestions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInterviewQuestion,
          [],
          {
            #userContentSummary: userContentSummary,
            #answeredQuestions: answeredQuestions,
          },
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateInterviewQuestion,
            [],
            {
              #userContentSummary: userContentSummary,
              #answeredQuestions: answeredQuestions,
            },
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [VoiceRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecordRepository extends _i1.Mock
    implements _i8.VoiceRecordRepository {
  MockVoiceRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>
      getAllVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getAllVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.VoiceRecord>>(
              this,
              Invocation.method(
                #getAllVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, _i10.VoiceRecord>> getVoiceRecordById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRecordById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i9.Failure, _i10.VoiceRecord>>.value(
                _FakeEither_0<_i9.Failure, _i10.VoiceRecord>(
          this,
          Invocation.method(
            #getVoiceRecordById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, _i10.VoiceRecord>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> insertVoiceRecord(
          _i10.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #insertVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> updateVoiceRecord(
          _i10.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #updateVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> deleteVoiceRecord(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecord,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecord,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>
      searchVoiceRecords(String? query) => (super.noSuchMethod(
            Invocation.method(
              #searchVoiceRecords,
              [query],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.VoiceRecord>>(
              this,
              Invocation.method(
                #searchVoiceRecords,
                [query],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>
      getVoiceRecordsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getVoiceRecordsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.VoiceRecord>>(
              this,
              Invocation.method(
                #getVoiceRecordsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>
      getProcessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getProcessedVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.VoiceRecord>>(
              this,
              Invocation.method(
                #getProcessedVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>
      getUnprocessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getUnprocessedVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.VoiceRecord>>(
              this,
              Invocation.method(
                #getUnprocessedVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, List<_i10.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> markAsProcessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsProcessed,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #markAsProcessed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> markAsUnprocessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnprocessed,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #markAsUnprocessed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> deleteVoiceRecords(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecords,
          [ids],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecords,
            [ids],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i9.Failure, Map<String, dynamic>>>
      getRecordingStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getRecordingStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i9.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i9.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getRecordingStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i9.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [InterviewQuestionPool].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterviewQuestionPool extends _i1.Mock
    implements _i11.InterviewQuestionPool {
  MockInterviewQuestionPool() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> getQuestions(int? count) => (super.noSuchMethod(
        Invocation.method(
          #getQuestions,
          [count],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCustomQuestions(List<String>? questions) => super.noSuchMethod(
        Invocation.method(
          #addCustomQuestions,
          [questions],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getStatus() => (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i12.DatabaseService {
  @override
  _i4.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i3.Database>);

  @override
  _i4.Future<int> insert(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            data,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> querySingle(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<dynamic>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #querySingle,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> rawUpdate(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawUpdate,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<T> transaction<T>(
          _i4.Future<T> Function(_i3.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
        returnValueForMissingStub: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<int> getCount(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> clearTable(String? table) => (super.noSuchMethod(
        Invocation.method(
          #clearTable,
          [table],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDatabase() => (super.noSuchMethod(
        Invocation.method(
          #deleteDatabase,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
