// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/services/enhanced_audio_recording_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:record/src/record.dart' as _i7;
import 'package:record_platform_interface/record_platform_interface.dart'
    as _i2;
import 'package:voice_autobiography_flutter/data/services/xunfei_asr_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAmplitude_0 extends _i1.SmartFake implements _i2.Amplitude {
  _FakeAmplitude_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [XunfeiAsrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockXunfeiAsrService extends _i1.Mock implements _i3.XunfeiAsrService {
  MockXunfeiAsrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accumulatedText => (super.noSuchMethod(
        Invocation.getter(#accumulatedText),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#accumulatedText),
        ),
      ) as String);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isSessionActive => (super.noSuchMethod(
        Invocation.getter(#isSessionActive),
        returnValue: false,
      ) as bool);

  @override
  bool get isConnecting => (super.noSuchMethod(
        Invocation.getter(#isConnecting),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<Map<String, dynamic>> get recognitionResultStream =>
      (super.noSuchMethod(
        Invocation.getter(#recognitionResultStream),
        returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
      ) as _i5.Stream<Map<String, dynamic>>);

  @override
  String getFinalText() => (super.noSuchMethod(
        Invocation.method(
          #getFinalText,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getFinalText,
            [],
          ),
        ),
      ) as String);

  @override
  void archiveText() => super.noSuchMethod(
        Invocation.method(
          #archiveText,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAccumulatedText() => super.noSuchMethod(
        Invocation.method(
          #clearAccumulatedText,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> startRecognition({bool? clearHistory = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecognition,
          [],
          {#clearHistory: clearHistory},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> sendAudioData(
    _i6.Uint8List? audioData, {
    bool? isEnd = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAudioData,
          [audioData],
          {#isEnd: isEnd},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> stopRecognition() => (super.noSuchMethod(
        Invocation.method(
          #stopRecognition,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorder extends _i1.Mock implements _i7.AudioRecorder {
  MockAudioRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> start(
    _i2.RecordConfig? config, {
    required String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #start,
          [config],
          {#path: path},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i5.Stream<_i6.Uint8List>> startStream(_i2.RecordConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #startStream,
          [config],
        ),
        returnValue: _i5.Future<_i5.Stream<_i6.Uint8List>>.value(
            _i5.Stream<_i6.Uint8List>.empty()),
      ) as _i5.Future<_i5.Stream<_i6.Uint8List>>);

  @override
  _i5.Future<String?> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isRecording() => (super.noSuchMethod(
        Invocation.method(
          #isRecording,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isPaused() => (super.noSuchMethod(
        Invocation.method(
          #isPaused,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.InputDevice>> listInputDevices() => (super.noSuchMethod(
        Invocation.method(
          #listInputDevices,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.InputDevice>>.value(<_i2.InputDevice>[]),
      ) as _i5.Future<List<_i2.InputDevice>>);

  @override
  _i5.Future<_i2.Amplitude> getAmplitude() => (super.noSuchMethod(
        Invocation.method(
          #getAmplitude,
          [],
        ),
        returnValue: _i5.Future<_i2.Amplitude>.value(_FakeAmplitude_0(
          this,
          Invocation.method(
            #getAmplitude,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Amplitude>);

  @override
  _i5.Future<bool> isEncoderSupported(_i2.AudioEncoder? encoder) =>
      (super.noSuchMethod(
        Invocation.method(
          #isEncoderSupported,
          [encoder],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i2.RecordState> onStateChanged() => (super.noSuchMethod(
        Invocation.method(
          #onStateChanged,
          [],
        ),
        returnValue: _i5.Stream<_i2.RecordState>.empty(),
      ) as _i5.Stream<_i2.RecordState>);

  @override
  _i5.Stream<_i2.Amplitude> onAmplitudeChanged(Duration? interval) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAmplitudeChanged,
          [interval],
        ),
        returnValue: _i5.Stream<_i2.Amplitude>.empty(),
      ) as _i5.Stream<_i2.Amplitude>);

  @override
  List<int> convertBytesToInt16(
    _i6.Uint8List? bytes, [
    dynamic endian = _i6.Endian.little,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertBytesToInt16,
          [
            bytes,
            endian,
          ],
        ),
        returnValue: <int>[],
      ) as List<int>);
}
