// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/repositories/ai_generation_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:voice_autobiography_flutter/data/services/doubao_ai_service.dart'
    as _i2;
import 'package:voice_autobiography_flutter/domain/entities/autobiography.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DoubaoAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoubaoAiService extends _i1.Mock implements _i2.DoubaoAiService {
  MockDoubaoAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> analyzeAutobiographyStructure({
    required String? newContent,
    required List<Map<String, dynamic>>? currentChapters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeAutobiographyStructure,
          [],
          {
            #newContent: newContent,
            #currentChapters: currentChapters,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> generateAutobiography({
    required List<String>? voiceContents,
    _i4.AutobiographyStyle? style = _i4.AutobiographyStyle.narrative,
    int? wordCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAutobiography,
          [],
          {
            #voiceContents: voiceContents,
            #style: style,
            #wordCount: wordCount,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateAutobiography,
            [],
            {
              #voiceContents: voiceContents,
              #style: style,
              #wordCount: wordCount,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> optimizeAutobiography({
    required String? originalContent,
    _i4.OptimizationType? optimizationType = _i4.OptimizationType.clarity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeAutobiography,
          [],
          {
            #originalContent: originalContent,
            #optimizationType: optimizationType,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #optimizeAutobiography,
            [],
            {
              #originalContent: originalContent,
              #optimizationType: optimizationType,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateChapterContent({
    String? originalContent,
    required String? newVoiceContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateChapterContent,
          [],
          {
            #originalContent: originalContent,
            #newVoiceContent: newVoiceContent,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateChapterContent,
            [],
            {
              #originalContent: originalContent,
              #newVoiceContent: newVoiceContent,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateTitle(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateTitle,
          [content],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateTitle,
            [content],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateSummary(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateSummary,
          [content],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateSummary,
            [content],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateInterviewQuestion({
    required String? userContentSummary,
    required List<String>? answeredQuestions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateInterviewQuestion,
          [],
          {
            #userContentSummary: userContentSummary,
            #answeredQuestions: answeredQuestions,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateInterviewQuestion,
            [],
            {
              #userContentSummary: userContentSummary,
              #answeredQuestions: answeredQuestions,
            },
          ),
        )),
      ) as _i3.Future<String>);
}
