// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/repositories/voice_record_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i5;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/repositories/voice_record_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecordRepository extends _i1.Mock
    implements _i3.VoiceRecordRepository {
  MockVoiceRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>
      getAllVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getAllVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.VoiceRecord>>(
              this,
              Invocation.method(
                #getAllVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VoiceRecord>> getVoiceRecordById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVoiceRecordById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.VoiceRecord>>.value(
            _FakeEither_0<_i5.Failure, _i6.VoiceRecord>(
          this,
          Invocation.method(
            #getVoiceRecordById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.VoiceRecord>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> insertVoiceRecord(
          _i6.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #insertVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateVoiceRecord(
          _i6.VoiceRecord? voiceRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVoiceRecord,
          [voiceRecord],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateVoiceRecord,
            [voiceRecord],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteVoiceRecord(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecord,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecord,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>> searchVoiceRecords(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVoiceRecords,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.VoiceRecord>>(
          this,
          Invocation.method(
            #searchVoiceRecords,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>
      getVoiceRecordsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getVoiceRecordsByDateRange,
              [
                startDate,
                endDate,
              ],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.VoiceRecord>>(
              this,
              Invocation.method(
                #getVoiceRecordsByDateRange,
                [
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>
      getProcessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getProcessedVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.VoiceRecord>>(
              this,
              Invocation.method(
                #getProcessedVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>
      getUnprocessedVoiceRecords() => (super.noSuchMethod(
            Invocation.method(
              #getUnprocessedVoiceRecords,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.VoiceRecord>>(
              this,
              Invocation.method(
                #getUnprocessedVoiceRecords,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.VoiceRecord>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsProcessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsProcessed,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #markAsProcessed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsUnprocessed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsUnprocessed,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #markAsUnprocessed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteVoiceRecords(
          List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVoiceRecords,
          [ids],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteVoiceRecords,
            [ids],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getRecordingStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getRecordingStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getRecordingStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
