// Mocks generated by Mockito 5.4.6 from annotations
// in voice_autobiography_flutter/test/unit/bloc/recording/recording_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:voice_autobiography_flutter/core/errors/failures.dart' as _i5;
import 'package:voice_autobiography_flutter/domain/entities/voice_record.dart'
    as _i6;
import 'package:voice_autobiography_flutter/domain/usecases/recording_usecases.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGenerateAutobiographyUseCase_0 extends _i1.SmartFake
    implements _i2.GenerateAutobiographyUseCase {
  _FakeGenerateAutobiographyUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecordingUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingUseCases extends _i1.Mock implements _i2.RecordingUseCases {
  MockRecordingUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GenerateAutobiographyUseCase get generateAutobiographyUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#generateAutobiographyUseCase),
        returnValue: _FakeGenerateAutobiographyUseCase_0(
          this,
          Invocation.getter(#generateAutobiographyUseCase),
        ),
      ) as _i2.GenerateAutobiographyUseCase);

  @override
  _i4.Future<_i3.Either<_i5.Failure, String>> startRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, String>>.value(
            _FakeEither_1<_i5.Failure, String>(
          this,
          Invocation.method(
            #startRecording,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i3.Either<_i5.Failure, _i6.VoiceRecord>> stopRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, _i6.VoiceRecord>>.value(
            _FakeEither_1<_i5.Failure, _i6.VoiceRecord>(
          this,
          Invocation.method(
            #stopRecording,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, _i6.VoiceRecord>>);

  @override
  _i4.Future<_i3.Either<_i5.Failure, void>> pauseRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseRecording,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, void>>.value(
            _FakeEither_1<_i5.Failure, void>(
          this,
          Invocation.method(
            #pauseRecording,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i3.Either<_i5.Failure, void>> resumeRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #resumeRecording,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, void>>.value(
            _FakeEither_1<_i5.Failure, void>(
          this,
          Invocation.method(
            #resumeRecording,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i3.Either<_i5.Failure, void>> cancelRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i4.Future<_i3.Either<_i5.Failure, void>>.value(
            _FakeEither_1<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelRecording,
            [],
          ),
        )),
      ) as _i4.Future<_i3.Either<_i5.Failure, void>>);
}
